"""
The bill of materials, and the regulation behind it.

Regulation (EU) 2024/2847 (the Cyber Resilience Act) requires a software bill
of materials "in a commonly used and machine-readable format covering at the
very least the top-level dependencies". Vulnerability-reporting obligations
start on 11 September 2026 and the regulation applies in full from
11 December 2027.

Two kinds of test here, and the split is deliberate.

The structural ones run everywhere and hold the properties that make the
document useful: it describes what the build actually installs, it carries the
hashes the build verifies, and it is reproducible so two of them can be
diffed. Those are the things that break silently.

The schema check runs only where `jsonschema` and the official CycloneDX
schema are installed. Hand-reading a JSON schema is exactly the kind of
verification that feels done and is not, so where the real schema is available
it is used; where it is not, the test skips rather than pretending.
"""

import json
import os
import sys

import pytest

from core.version import APP_NAME, __version__
from tests.conftest import REPO_ROOT

sys.path.insert(0, os.path.join(REPO_ROOT, "packaging"))

import sbom   # noqa: E402


def lockfile_text() -> str:
    with open(os.path.join(REPO_ROOT, "requirements.lock"), encoding="utf-8") as fh:
        return fh.read()


# ── Reading the lockfile ──────────────────────────────────────────────────

class TestItDescribesWhatTheBuildInstalls:
    """
    The lockfile is the input, not the installed environment. A build runs
    `pip install --require-hashes -r requirements.lock`, so that file is what
    ends up in the binary; a document generated by introspecting whatever is
    importable on the build machine would describe a different set of packages
    and nobody would notice.
    """

    def test_every_locked_package_is_a_component(self):
        packages = sbom.parse_lockfile(lockfile_text())
        names = {p["name"] for p in packages}
        assert {"psutil", "plyer"} <= names

    def test_each_component_carries_its_pinned_version(self):
        versions = {p["name"]: p["version"] for p in sbom.parse_lockfile(lockfile_text())}
        assert versions["psutil"].count(".") >= 1
        assert all(v and not v.startswith("=") for v in versions.values())

    def test_the_hashes_are_the_ones_the_build_verifies(self):
        # `--require-hashes` is what makes the build reproducible. Carrying the
        # same hashes into the SBOM is what stops the document and the binary
        # describing different artifacts.
        packages = {p["name"]: p for p in sbom.parse_lockfile(lockfile_text())}
        assert packages["plyer"]["hashes"]
        for value in packages["plyer"]["hashes"]:
            assert len(value) == 64 and all(c in "0123456789abcdef" for c in value)

    def test_a_hash_inside_a_comment_is_not_read_as_one(self):
        # pip-compile writes "# via protbot (pyproject.toml)" under each entry.
        # A commented-out hash must not become a claim about the artifact.
        text = (
            "psutil==7.2.2 \\\n"
            "    --hash=sha256:" + "a" * 64 + "\n"
            "    # --hash=sha256:" + "b" * 64 + "\n"
            "    # via protbot (pyproject.toml)\n"
        )
        packages = sbom.parse_lockfile(text)
        assert packages[0]["hashes"] == ["a" * 64]

    def test_packages_come_out_in_a_stable_order(self):
        text = ("zebra==1.0\n" "alpha==2.0\n" "Middle==3.0\n")
        assert [p["name"] for p in sbom.parse_lockfile(text)] == \
            ["alpha", "Middle", "zebra"]

    def test_an_unparseable_lockfile_yields_nothing_rather_than_guessing(self):
        assert sbom.parse_lockfile("this is not a lockfile\n") == []


# ── The document ──────────────────────────────────────────────────────────

class TestTheDocument:

    @pytest.fixture
    def document(self):
        return sbom.build_sbom(lockfile_text())

    def test_it_says_which_format_and_version_it_is(self, document):
        # A consumer reads these two fields before anything else.
        assert document["bomFormat"] == "CycloneDX"
        assert document["specVersion"] == "1.5"

    def test_it_names_the_product_itself_not_only_its_dependencies(self, document):
        component = document["metadata"]["component"]
        assert component["type"] == "application"
        assert component["name"] == APP_NAME
        assert component["version"] == __version__

    def test_the_version_tracks_the_one_source_of_truth(self, document):
        # core/version.py is the single definition. An SBOM describing a
        # version that was never built is a compliance document with a
        # falsehood in it.
        assert __version__ in document["metadata"]["component"]["purl"]

    def test_every_component_has_a_package_url(self, document):
        # The purl is how a scanner joins a component to an advisory. Without
        # one the document lists names and gets no vulnerability matches.
        for component in document["components"]:
            assert component["purl"].startswith("pkg:pypi/")
            assert component["bom-ref"]

    def test_package_urls_are_normalised(self):
        # PEP 503: "Foo.Bar", "foo-bar" and "foo_bar" are one package on PyPI,
        # and the purl spec is defined in terms of the normalised name. An
        # unnormalised one silently matches no advisories.
        assert sbom._purl("Foo.Bar_baz", "1.0") == "pkg:pypi/foo-bar-baz@1.0"

    def test_component_hashes_are_labelled_with_their_algorithm(self, document):
        for component in document["components"]:
            for entry in component.get("hashes", []):
                assert entry["alg"] == "SHA-256"
                assert len(entry["content"]) == 64

    def test_the_licence_matches_what_the_project_actually_is(self, document):
        # Proprietary, and stated. pyproject.toml says the same thing; a
        # document claiming a permissive licence would be worse than none.
        licences = document["metadata"]["component"]["licenses"]
        assert "Proprietary" in json.dumps(licences)

    def test_it_is_reproducible(self):
        # Two runs over the same lockfile must be byte-identical, or CI cannot
        # diff a regenerated document against a committed one and mean
        # anything by the answer.
        from datetime import datetime, timezone

        moment = datetime(2026, 9, 3, 12, 0, 0, tzinfo=timezone.utc)
        text = lockfile_text()
        first = sbom.render(sbom.build_sbom(text, now=moment))
        second = sbom.render(sbom.build_sbom(text, now=moment))
        assert first == second

    def test_the_serial_number_is_a_urn_uuid(self, document):
        assert document["serialNumber"].startswith("urn:uuid:")


# ── The command line ──────────────────────────────────────────────────────

class TestTheGenerator:

    def test_check_reports_without_writing(self, capsys, tmp_path):
        assert sbom.main(["--check"]) == 0
        assert "component(s)" in capsys.readouterr().out
        assert not list(tmp_path.iterdir())

    def test_it_writes_a_file_that_parses_as_json(self, tmp_path):
        out = tmp_path / "bom.json"
        assert sbom.main(["--output", str(out)]) == 0
        assert json.loads(out.read_text(encoding="utf-8"))["bomFormat"] == "CycloneDX"

    def test_an_empty_bill_of_materials_is_a_failure_not_a_pass(self, tmp_path):
        # If the lockfile format ever changes under this, the honest outcome is
        # a failed build. A compliance document that quietly describes nothing
        # is worse than a missing one, because it looks like it was produced.
        empty = tmp_path / "requirements.lock"
        empty.write_text("# nothing here\n", encoding="utf-8")
        assert sbom.main(["--lockfile", str(empty),
                          "--output", str(tmp_path / "bom.json")]) == 1
        assert not (tmp_path / "bom.json").exists()

    def test_a_missing_lockfile_is_reported_not_raised(self, tmp_path):
        assert sbom.main(["--lockfile", str(tmp_path / "nope.lock")]) == 1


# ── Against the real schema ───────────────────────────────────────────────

def _official_schema():
    """The CycloneDX 1.5 schema, or None if it is not installed here."""
    try:
        import glob

        import cyclonedx.schema
    except ImportError:
        return None

    base = os.path.dirname(cyclonedx.schema.__file__)
    matches = [p for p in glob.glob(os.path.join(base, "**", "*.json"), recursive=True)
               if "bom-1.5" in os.path.basename(p)]
    return (base, matches[0]) if matches else None


class TestItValidatesAgainstTheRealSchema:
    """
    Skipped where the schema is not installed. Reading a JSON schema by hand
    and concluding the document conforms is the kind of check that feels done
    and is not — so where the real thing is available, it is used.
    """

    def test_the_document_conforms(self):
        pytest.importorskip("jsonschema")
        found = _official_schema()
        if not found:
            pytest.skip("the official CycloneDX schema is not installed")

        import glob

        from jsonschema import Draft7Validator, RefResolver

        base, schema_path = found
        with open(schema_path, encoding="utf-8") as fh:
            schema = json.load(fh)

        # The schema $refs its siblings (spdx, jsf) by filename.
        store = {}
        for path in glob.glob(os.path.join(base, "*.json")):
            with open(path, encoding="utf-8") as fh:
                sibling = json.load(fh)
            store[os.path.basename(path)] = sibling
            if "$id" in sibling:
                store[sibling["$id"]] = sibling

        document = sbom.build_sbom(lockfile_text())
        validator = Draft7Validator(
            schema,
            resolver=RefResolver(base_uri=schema.get("$id", ""),
                                 referrer=schema, store=store),
        )
        errors = [f"{list(e.path)}: {e.message}" for e in validator.iter_errors(document)]
        assert not errors, "\n".join(errors)
