"""
models.py — Minimal Pydantic request/response models.

Key design: single-char JSON keys to shrink every payload.
Upload cycle: every 30 minutes.

The clients are core/syncproto.py (desktop) and
android/core/.../Sync.kt (Android). Both are written against the semantics
below and tested against them; a server that implements this file differently
will produce wrong totals rather than errors, so read the three notes before
building one.

  1. **Uploads are cumulative, not deltas.** `UploadReq.a` carries each app's
     running total for the day named in `z`, not the seconds since the last
     upload. Store it with `max(stored, received)` per (device, app, date).
     That makes a retry after a lost response a no-op, makes out-of-order
     arrivals settle correctly, and lets a device that was offline for six
     hours catch up in one request. Adding deltas instead double-counts every
     retried upload, and there is no acknowledgement scheme that fixes it
     without becoming a transaction log.

  2. **The date is the client's, not the server's.** `UploadReq.z` is the
     device's local date and must be stored verbatim. A server bucketing by
     its own UTC date puts a Belgrade evening into tomorrow, and the user
     watches their daily limit reset at 2am.

  3. **App identity is the canonical key.** `AppSyncReq.a` sends
     `syncproto.canonical_app_key(name)`, not the display name — the desktop
     knows the app as "Discord.exe" and the phone as "com.discord", and they
     have to land in one row. The server matches on that key within a device
     group and assigns one server id.

`SyncResp.apps` returns the group total per app, including the requesting
device's own last upload. Clients subtract their own contribution before
merging; see syncproto.merge_app_total for why that is not the same as taking
the larger of the two numbers.

  4. **The device id is not a credential (AUDIT SF-09).** It is echoed back in
     every response and shown to the user in the Devices tab, and it travels
     in the body of every request below — a server that trusts it alone is
     trusting a value an eavesdropper on any of those requests already has.
     `RegisterResp.tok` is the credential: a per-device secret, generated by
     the server and never derivable from the id, that the client stores and
     sends as `Authorization: Bearer <token>` on every call after
     registration. The server must check it — matching it to the `d` in the
     request body — before reading or writing that device's data, and must
     not accept a request with a valid-looking id and no token, or a token
     that does not match the id it came with. Registration is the only call
     with no token to check, because it is the call that issues one.
"""

from pydantic import BaseModel


# ── Registration ───────────────────────────────────────────────────────────────

class RegisterReq(BaseModel):
    e: str | None = None   # email — discarded immediately after response
    n: str | None = None   # device label, shown only in the user's device list

class RegisterResp(BaseModel):
    id: str                   # 24-char device_id
    tok: str                  # per-device secret; see note 4 above


# ── App list sync (sent once, or when tracked apps change) ────────────────────
# Each entry: [local_db_id, name, category]
# Example: [[1,"Discord","Social"],[2,"VS Code","Development"]]

class AppSyncReq(BaseModel):
    d: str                    # device_id
    a: list[list]             # [[local_id, name, category], ...]

class AppSyncResp(BaseModel):
    m: dict                   # {"local_id": server_id, ...}


# ── 30-minute usage upload ────────────────────────────────────────────────────
# "a" contains only apps that had usage > 0 in this window.
# Each entry: [server_app_id, seconds_used]
# Example: [[42,1800],[43,270]]

class UploadReq(BaseModel):
    d: str                    # device_id
    t: int                    # period end — unix timestamp (int, not ISO string)
    a: list[list]             # [[server_app_id, seconds], ...]  only s>0

class UploadResp(BaseModel):
    ok: int = 1


# ── Cross-device sync response ────────────────────────────────────────────────

class SyncResp(BaseModel):
    apps: dict                # {server_app_id: total_sec_today}
    devices: int              # number of linked devices


# ── Device linking ────────────────────────────────────────────────────────────

class LinkNewResp(BaseModel):
    k: str                    # 8-char key, valid 5 minutes

class LinkJoinReq(BaseModel):
    d: str                    # joining device_id
    k: str                    # key from the host device

class LinkJoinResp(BaseModel):
    ok: int = 1
    grp: str                  # shared group id


# ── Global anonymous stats ────────────────────────────────────────────────────

class GlobalStatsResp(BaseModel):
    # {category: {sec_today, users_today}}
    cats: dict
    total_users: int
